# Generated by Django 4.1.2 on 2022-10-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vecinos',
            new_name='Vecino',
        ),
    ]
